<?php

declare(strict_types=1);

use MkGrow\ContentControl\SDTRegistry;
use MkGrow\ContentControl\SDTConfig;
use MkGrow\ContentControl\ContentControl;
use PhpOffice\PhpWord\Element\Section;

describe('SDTRegistry - ID Generation', function () {
    test('generates unique 8-digit ID', function () {
        $registry = new SDTRegistry();
        $id = $registry->generateUniqueId();
        
        expect($id)->toMatch('/^\d{8}$/');
        expect((int) $id)->toBeGreaterThanOrEqual(10000000);
        expect((int) $id)->toBeLessThanOrEqual(99999999);
    });

    test('generates different IDs in consecutive calls', function () {
        $registry = new SDTRegistry();
        $id1 = $registry->generateUniqueId();
        $id2 = $registry->generateUniqueId();
        
        expect($id1)->not->toBe($id2);
    });

    test('generates 10,000 IDs without duplicates', function () {
        $registry = new SDTRegistry();
        $ids = [];
        
        for ($i = 0; $i < 10000; $i++) {
            $id = $registry->generateUniqueId();
            $registry->markIdAsUsed($id); // Mark as used for next iteration
            $ids[$id] = true;
        }
        
        // If all are unique, count($ids) should be 10,000
        expect(count($ids))->toBe(10000);
    });

    test('generated ID is not marked as used until register()', function () {
        $registry = new SDTRegistry();
        $id = $registry->generateUniqueId();
        
        // Generated ID is not marked as used until registered
        expect($registry->isIdUsed($id))->toBeFalse();
        
        // After registering, ID should be marked as used
        $section = createSection();
        $registry->register($section, new SDTConfig(id: $id));
        expect($registry->isIdUsed($id))->toBeTrue();
    });
});

describe('SDTRegistry - Element Registration', function () {
    test('registers element with config', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        $config = new SDTConfig(id: '12345678');
        
        $registry->register($section, $config);
        
        expect($registry->count())->toBe(1);
        expect($registry->has($section))->toBeTrue();
    });

    test('registers multiple elements', function () {
        $registry = new SDTRegistry();
        $section1 = createSection();
        $section2 = createSection();
        
        $registry->register($section1, new SDTConfig(id: '12345678'));
        $registry->register($section2, new SDTConfig(id: '87654321'));
        
        expect($registry->count())->toBe(2);
        expect($registry->has($section1))->toBeTrue();
        expect($registry->has($section2))->toBeTrue();
    });

    test('rejects duplicate element', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: '12345678'));
        
        expect(fn() => $registry->register($section, new SDTConfig(id: '87654321')))
            ->toThrow(InvalidArgumentException::class, 'already registered');
    });

    test('rejects duplicate ID', function () {
        $registry = new SDTRegistry();
        $section1 = createSection();
        $section2 = createSection();
        
        $registry->register($section1, new SDTConfig(id: '12345678'));
        
        expect(fn() => $registry->register($section2, new SDTConfig(id: '12345678')))
            ->toThrow(InvalidArgumentException::class, 'already in use');
    });

    test('allows registering ID generated by generateUniqueId', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        // Generate a unique ID
        $generatedId = $registry->generateUniqueId();
        
        // Should allow registering element with generated ID (not reserved)
        $registry->register($section, new SDTConfig(id: $generatedId));
        
        // After registration, ID should be marked as used
        expect($registry->isIdUsed($generatedId))->toBeTrue();
        expect($registry->count())->toBe(1);
    });

    test('accepts config with empty ID', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        $config = new SDTConfig(id: '');
        
        $registry->register($section, $config);
        
        expect($registry->count())->toBe(1);
    });

    // Edge case: Multiple elements can have empty IDs because the duplicate check
    // in SDTRegistry::register explicitly skips empty IDs.
    // This allows elements without IDs to be registered multiple times.
    // When the document is saved, Word will auto-generate unique IDs if needed.
    test('multiple elements with empty ID do not cause error', function () {
        $registry = new SDTRegistry();
        $section1 = createSection();
        $section2 = createSection();
        
        $registry->register($section1, new SDTConfig(id: ''));
        $registry->register($section2, new SDTConfig(id: ''));
        
        expect($registry->count())->toBe(2);
    });
});

describe('SDTRegistry - getAll', function () {
    test('returns empty array when no records', function () {
        $registry = new SDTRegistry();
        
        expect($registry->getAll())->toBe([]);
    });

    test('returns correct tuples', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        $config = new SDTConfig(id: '12345678', alias: 'Test');
        
        $registry->register($section, $config);
        
        $all = $registry->getAll();
        
        expect($all)->toHaveCount(1);
        expect($all[0]['element'])->toBe($section);
        expect($all[0]['config'])->toBe($config);
    });

    test('returns multiple tuples', function () {
        $registry = new SDTRegistry();
        $section1 = createSection();
        $section2 = createSection();
        $config1 = new SDTConfig(id: '12345678');
        $config2 = new SDTConfig(id: '87654321');
        
        $registry->register($section1, $config1);
        $registry->register($section2, $config2);
        
        $all = $registry->getAll();
        
        expect($all)->toHaveCount(2);
        expect($all[0]['element'])->toBe($section1);
        expect($all[1]['element'])->toBe($section2);
    });
});

describe('SDTRegistry - getConfig', function () {
    test('returns config of registered element', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        $config = new SDTConfig(id: '12345678', alias: 'Test');
        
        $registry->register($section, $config);
        
        $retrieved = $registry->getConfig($section);
        
        expect($retrieved)->toBe($config);
    });

    test('returns null for unregistered element', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        expect($registry->getConfig($section))->toBeNull();
    });

    test('distinguishes different elements', function () {
        $registry = new SDTRegistry();
        $section1 = createSection();
        $section2 = createSection();
        $config1 = new SDTConfig(id: '12345678', alias: 'Section 1');
        $config2 = new SDTConfig(id: '87654321', alias: 'Section 2');
        
        $registry->register($section1, $config1);
        $registry->register($section2, $config2);
        
        expect($registry->getConfig($section1))->toBe($config1);
        expect($registry->getConfig($section2))->toBe($config2);
    });
});

describe('SDTRegistry - has', function () {
    test('returns true for registered element', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: '12345678'));
        
        expect($registry->has($section))->toBeTrue();
    });

    test('returns false for unregistered element', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        expect($registry->has($section))->toBeFalse();
    });
});

describe('SDTRegistry - isIdUsed', function () {
    test('returns false for generated ID only (without register)', function () {
        $registry = new SDTRegistry();
        $id = $registry->generateUniqueId();
        
        // Generated ID is not marked as used until registered
        expect($registry->isIdUsed($id))->toBeFalse();
        
        // After registering, should be marked as used
        $section = createSection();
        $registry->register($section, new SDTConfig(id: $id));
        expect($registry->isIdUsed($id))->toBeTrue();
    });

    test('returns true for registered config ID', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: '12345678'));
        
        expect($registry->isIdUsed('12345678'))->toBeTrue();
    });

    test('returns false for unused ID', function () {
        $registry = new SDTRegistry();
        
        expect($registry->isIdUsed('99999999'))->toBeFalse();
    });

    test('does not mark empty ID as used', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: ''));
        
        expect($registry->isIdUsed(''))->toBeFalse();
    });
});

describe('SDTRegistry - count', function () {
    test('returns 0 for empty registry', function () {
        $registry = new SDTRegistry();
        
        expect($registry->count())->toBe(0);
    });

    test('returns correct count', function () {
        $registry = new SDTRegistry();
        
        $registry->register(createSection(), new SDTConfig(id: '12345678'));
        expect($registry->count())->toBe(1);
        
        $registry->register(createSection(), new SDTConfig(id: '87654321'));
        expect($registry->count())->toBe(2);
    });
});

describe('SDTRegistry - clear', function () {
    test('clears all records', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: '12345678'));
        expect($registry->count())->toBe(1);
        
        $registry->clear();
        
        expect($registry->count())->toBe(0);
        expect($registry->has($section))->toBeFalse();
        expect($registry->isIdUsed('12345678'))->toBeFalse();
    });

    test('allows registering again after clear', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        
        $registry->register($section, new SDTConfig(id: '12345678'));
        $registry->clear();
        
        // Should allow using same ID again
        $registry->register($section, new SDTConfig(id: '12345678'));
        
        expect($registry->count())->toBe(1);
    });
});

describe('SDTRegistry - Performance', function () {
    test('registers 1,000 elements without errors', function () {
        $registry = new SDTRegistry();
        $sections = [];
        
        // Create elements
        for ($i = 0; $i < 1000; $i++) {
            $sections[] = createSection();
        }
        
        // Register
        foreach ($sections as $i => $section) {
            $id = str_pad((string) (10000000 + $i), 8, '0', STR_PAD_LEFT);
            $registry->register($section, new SDTConfig(id: $id));
        }
        
        expect($registry->count())->toBe(1000);
    });
});
describe('SDTRegistry - Markers', function () {
    test('register generates marker automatically', function () {
        $registry = new SDTRegistry();
        $section = createSection();
        $config = new SDTConfig(id: '12345678');

        $registry->register($section, $config);

        $marker = $registry->getMarkerForElement($section);

        expect($marker)->not->toBeNull();
        expect($marker)->toMatch('/^sdt-marker-\d+-[a-f0-9]{8}$/');
    });

    test('getAllMarkers returns all markers', function () {
        $registry = new SDTRegistry();
        
        $section1 = createSection();
        $section2 = createSection();
        
        $registry->register($section1, new SDTConfig(id: '11111111'));
        $registry->register($section2, new SDTConfig(id: '22222222'));

        $markers = $registry->getAllMarkers();

        expect(count($markers))->toBe(2);
        
        // Verify structure
        foreach ($markers as $objectId => $markerId) {
            expect($objectId)->toBeInt();
            expect($markerId)->toMatch('/^sdt-marker-\d+-[a-f0-9]{8}$/');
        }
    });

    test('getMarkerForElement returns null for unregistered element', function () {
        $registry = new SDTRegistry();
        $section = createSection();

        $marker = $registry->getMarkerForElement($section);

        expect($marker)->toBeNull();
    });

    test('markers are unique for each element', function () {
        $registry = new SDTRegistry();
        
        $section1 = createSection();
        $section2 = createSection();
        
        $registry->register($section1, new SDTConfig(id: '11111111'));
        $registry->register($section2, new SDTConfig(id: '22222222'));

        $marker1 = $registry->getMarkerForElement($section1);
        $marker2 = $registry->getMarkerForElement($section2);

        expect($marker1)->not->toBe($marker2);
    });
});